---
title: "COVID-19 in Malaysia"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    navbar:
          - {title: "About me", icon: "fa-github", href: "https://github.com/fyii200", align: left}
    social: menu
    fig_mobile: FALSE
date: <span style="font-size:0.8em;">`r format(Sys.Date(), '%d %b %Y')` </span>
---

```{r setup, include=FALSE}
## load relevant functions, packages ##
# install.packages("waffle", repos = "https://cinc.rud.is")
# install.packages('dygraph')
# install.packages('dplyr)

library(RColorBrewer)
library(waffle)
library(dplyr)
library(dygraphs)
library(xts)
source('functions/data_update.R')
source('functions/dygraph.plot.R')

### DAILY CASES, TESTS, DEATHS, etc. ###
## read raw data (worldwide) and configure data frame named 'mys'
# mys <- read.csv('data/mys.csv'); mys <- mys[,-1]
# # update data!
# mys <- data_update(mys)
world<-read.csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')
mys <- world[which(world$iso_code=='MYS'),]
mys$date <- as.Date(mys$date)

### VACCINATION DATA ###
# data <- 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/Malaysia.csv'
# d$date <- as.Date(d$date)
data <- 'data/vaccine.csv'
d <- read.csv(data); d<-d[,-1]
d$date <- as.Date(d$date, '%d/%m/%Y')
```


Daily summary {data-icon="fa-table"}
=========================================

Row {data-height=300}
-----------------------------------------

### Vaccinations - Daily Total & Cumulative Total {.no-mobile}
```{r include=FALSE}
source('vaccinations/daily_new_doses.R')
col <- brewer.pal(9,'Blues')[c(5,8)]   
```
<span style="font-size:1.5em;"> **People vaccinated ** </span>
<span style="color:grey;"> *up to & including `r format(max(x), '%d %b %Y')`*</span> 

<span style="font-size:1em;"> New 1st dose | </span> <span style="font-size:0.9em; color:grey;"> &nbsp; cumulative total </span>  
<span style="font-size:2.5em; color:`r col[1]`;"> **+`r new.y1`** </span> <span style="font-size:2.5em;"> | </span> &nbsp;
<span style="font-size:1.5em; color:`r col[1]`;"> **`r format( cumulative_1st_dose, scientific = F, big.mark = ',')`** </span>
 
 
<span style="font-size:1em;"> New 2nd dose | </span> <span style="font-size:0.9em; color:grey;"> &nbsp; cumulative total </span>  
<span style="font-size:2.5em; color:`r col[2]`;"> **+`r new.y2`** </span> <span style="font-size:2.5em;"> | </span> &nbsp;
<span style="font-size:1.5em; color:`r col[2]`;"> **`r format( cumulative_2nd_dose, scientific = F, big.mark = ',')`** </span>
  

### Percentage of minimum target population (23.2m) vaccinated {.no-mobile}
```{r echo=FALSE}
source('summary/squareplot.R')
p(leg.position='')
```

<span style="font-size:1em;"> 1st dose </span>  
<span style="font-size:1.5em; color:`r col[1]`; text-decoration:underline"> **`r target_y1`%** </span>

<span style="font-size:1em;"> 2nd dose </span>  
<span style="font-size:1.5em; color:`r col[2]`; text-decoration:underline"> **`r target_y2`%** </span>




### Vaccinations - Daily Total & Cumulative Total {.mobile}
```{r include=FALSE}
source('vaccinations/daily_new_doses.R')
col <- brewer.pal(9,'Blues')[c(5,8)]   
```
<span style="font-size:1.5em;"> **People vaccinated ** </span>
<span style="color:grey;"> *up to `r format(max(x), '%d %b %Y')`*</span> 

<span style="font-size:1em;"> New 1st dose | </span> <span style="font-size:0.9em; color:grey;"> &nbsp; cumulative total </span>  
<span style="font-size:2em; color:`r col[1]`;"> **+`r new.y1`** </span> <span style="font-size:2.5em;"> | </span> &nbsp;
<span style="font-size:1.2em; color:`r col[1]`;"> **`r format( cumulative_1st_dose, scientific = F, big.mark = ',')`** </span>
 
 
<span style="font-size:1em;"> New 2nd dose | </span> <span style="font-size:0.9em; color:grey;"> &nbsp; cumulative total </span>  
<span style="font-size:2em; color:`r col[2]`;"> **+`r new.y2`** </span> <span style="font-size:2.5em;"> | </span> &nbsp;
<span style="font-size:1.2em; color:`r col[2]`;"> **`r format( cumulative_2nd_dose, scientific = F, big.mark = ',')`** </span>


### Percentage of minimum target population (23.2m) vaccinated {.mobile}
```{r echo=FALSE}
source('summary/squareplot.R')
p(leg.position='bottom')
```

<span style="font-size:1em;"> &nbsp; 1st </span> &nbsp; | &nbsp; <span style="font-size:1em;"> 2nd dose </span>

<span style="font-size:1.3em; color:`r col[1]`; text-decoration:underline"> &nbsp; **`r target_y1`%** </span> &nbsp; | &nbsp;
<span style="font-size:1.3em; color:`r col[2]`; text-decoration:underline"> **`r target_y2`%** </span>





Row {data-height=450}
-----------------------------------------
### Cases
```{r include=FALSE}
source('cases/daily_new_cases.R')

label <- paste( format(
                   weekchange * 7, scientific=F, big.mark=','), 
                   ' (', 
                   weekchange_perc, 
                   '%)', 
         sep='')
```

<span style="font-size:1.5em;"> **People tested positive** </span>

Daily <span style="font-size:0.9em; color:grey;"> *`r format( max(x, na.rm = T), '%d %b %Y')`*</span>  
<span style="font-size:1.5em"> **+`r dailynew`** </span>

7-day total <span style="font-size:0.8em; color:grey;"> *(week ending `r lastlastdate`)*</span>  
<span style="font-size:1.3em"> **`r format( sum(lastlast7cases), scientific = F, big.mark = ',')`** </span>

7-day total <span style="font-size:0.8em; color:grey;"> *(week ending `r format(max(x), '%d %b')`)*</span>  
<span style="font-size:1.3em"> **`r format( sum(last7cases), scientific = F, big.mark = ',')`** </span> &nbsp;
<span style="font-size:1em; color:`r arrowcol`;"> **`r ifelse( weekchange >= 0, print('▲'), print('▲'))`  `r label`**</span>

#### 
```{r echo=FALSE, fig.width=3.5, fig.height=1}
# make empty plot then add smoothed line
par(mar = c(1, 0.3, 0, 0.3), las = 0)
plot(x, y, 
     bty = 'n', 
     xaxt = 'n', 
     yaxt = 'n', 
     type = 'n', 
     xlab = '', 
     ylab = '', 
     ylim = c(0, max(mys$new_cases_smoothed, na.rm = T) ) 
     )

axis(side = 1, 
     labels = format(xtlab, '%b'), 
     at = xtlab, 
     tick=F, 
     col.axis='gray56', 
     cex.axis=0.6, 
     padj=-3)

lines(x, mys$new_cases_smoothed, col=col[2], lwd=2)
```
